name: Swiss Oxyhydrogen Energy
instance: 41
topics:
  edge:
    subscribe:
      all: a/admin/cmd/all
      cmd: a/admin/cmd/CLIENTID
      rsp: a/admin/rsp/CLIENTID
      out: PROJECTID/INSTANCE/out/CLIENTID
    publish:
      rsp: a/admin/rsp/CLIENTID
      inp: PROJECTID/INSTANCE/inp/CLIENTID/USERID/oxy_edge
      cod: PROJECTID/INSTANCE/cod/CLIENTID
      msg: PROJECTID/INSTANCE/msg/CLIENTID
clients:
  arduino_gm:  enabled
  arduino5:    enabled
  hmi:         enabled
  controller:  enabled
  drupal:      enabled
