name: SAFIRE LAB
instance: 40
topics:
  edge:
    subscribe:
      all: a/cmd/all
      cmd: a/cmd/CLIENTID
      rsp: a/rsp/CLIENTID
      out: PROJECTID/out/CLIENTID
    publish:
      rsp: a/rsp/CLIENTID
      inp: PROJECTID/inp/CLIENTID/USERID/sl_lt
      cod: PROJECTID/cod/CLIENTID
      msg: PROJECTID/msg/CLIENTID
clients:
  dataq1:        enabled
  hmi-sl:        enabled
  controller-sl: enabled
  drupal:        enabled
