name: SAFIRE LAB
instance: 42
topics:
  edge:
    subscribe:
      all: a/admin/cmd/all
      cmd: a/admin/cmd/CLIENTID
      rsp: a/admin/rsp/CLIENTID
      out: PROJECTID/INSTANCE/out/CLIENTID
    publish:
      rsp: a/admin/rsp/CLIENTID
      inp: PROJECTID/INSTANCE/inp/CLIENTID/USERID/cabin_lt
      cod: PROJECTID/INSTANCE/cod/CLIENTID
      msg: PROJECTID/INSTANCE/msg/CLIENTID
clients:
  epiclc:      enabled
  arduino2:    enabled
  arduino3:    enabled
  arduino4:    enabled
  arduino5:    enabled
  arduino6:    enabled
  hmi:         enabled
  controller:  enabled
  drupal:      enabled
