name: Swiss Oxyhydrogen Energy
edgeId: oxy_edge
msgId: oxy_msg
clients:
  arduino_gm:     enabled
  arduino2:       enabled
  arduino6:       enabled
  hmi-oxy:        enabled
  controller-oxy: enabled
  drupal:         enabled
