name: Swiss Oxyhydrogen Energy
edgeId: oxy_edge
msgId: oxy_msg
clients:
  arduino_gm:  enabled
  arduino4:    enabled
  arduino6:    enabled
  hmi-oxy:     enabled
  control-oxy: enabled
  drupal:      enabled
