name: Cabin in Red Feather
instance: 42
topics:
  edge:
    subscribe:
      all: a/cmd/all
      cmd: a/cmd/CLIENTID
      rsp: a/rsp/CLIENTID
      out: PROJECTID/out/CLIENTID
    publish:
      rsp: a/rsp/CLIENTID
      inp: PROJECTID/inp/CLIENTID/USERID/cb_edge
      cod: PROJECTID/cod/CLIENTID
      msg: PROJECTID/msg/CLIENTID
clients:
  epiclc:     enabled
  arduino2:   enabled
  arduino3:   disabled
  arduino4:   enabled
  arduino5:   disabled
  hmi:        enabled
  controller: enabled
  drupal:     disabled
